[language-server.scls]
command = "simple-completion-language-server"
args = []

[language-server.cspell]
command = "cspell-lsp"
args = ["--stdio"]

[language-server.sql]
command = "sqls"
args = []

[language-server.oxlint]
command = "pnpm"
args = ["exec", "oxlint", "--lsp"]

[language-server.oxfmt]
command = "oxfmt"
args = ["--lsp"]

[language-server.emmet]
command = "emmet-language-server"
args = ["--stdio"]

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[[language-server.vscode-json-language-server.config.json.schemas]]
fileMatch = ["tsconfig.json", "tsconfig*.json"]
url = "https://json.schemastore.org/tsconfig.json"

[[language-server.vscode-json-language-server.config.json.schemas]]
fileMatch = ["package.json"]
url = "https://json.schemastore.org/package.json"

[[language]]
name = "css"
roots = ["package.json"]
language-servers = [
  { name = "vscode-css-language-server", except-features = [
    "format",
  ] },
  "emmet",
  "oxlint",
  "oxfmt",
  "tailwindcss-ls",
  "cspell",
  "scls",
]
auto-format = true

[[language]]
name = "docker-compose"
roots = ["package.json"]
language-servers = [
  "docker-compose-langserver",
  { name = "yaml-language-server", except-features = [
    "format",
  ] },
  "oxlint",
  "oxfmt",
  "cspell",
  "scls",
]
auto-format = true

[[language]]
name = "html"
roots = ["package.json"]
language-servers = [
  { name = "vscode-html-language-server", except-features = [
    "format",
  ] },
  "emmet",
  "oxlint",
  "oxfmt",
  "tailwindcss-ls",
  "cspell",
  "scls",
]
auto-format = true

[[language]]
name = "json"
roots = ["package.json"]
language-servers = [
  { name = "vscode-json-language-server", except-features = [
    "format",
  ] },
  "oxlint",
  "oxfmt",
  "cspell",
  "scls",
]
auto-format = true

[[language]]
name = "jsonc"
roots = ["package.json"]
language-servers = [
  { name = "vscode-json-language-server", except-features = [
    "format",
  ] },
  "oxlint",
  "oxfmt",
  "cspell",
  "scls",
]
auto-format = true

[[language]]
name = "markdown"
roots = ["package.json"]
language-servers = ["marksman", "markdown-oxide", "oxlint", "oxfmt", "cspell", "scls"]
auto-format = true

[[language]]
name = "nix"
roots = ["package.json"]
language-servers = ["nil", "nixd", "cspell", "scls"]
formatter = { command = "nixfmt" }
auto-format = true

[[language]]
name = "sql"
language-servers = ["sqls", "cspell", "scls"]

[[language]]
name = "toml"
roots = ["package.json"]
language-servers = [
  { name = "taplo", except-features = [
    "format",
  ] },
  { name = "tombi", except-features = [
    "format",
  ] },
  "oxlint",
  "oxfmt",
  "cspell",
  "scls",
]
auto-format = true

[[language]]
name = "tsx"
roots = ["package.json"]
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "emmet",
  "oxfmt",
  "oxlint",
  "tailwindcss-ls",
  "cspell",
  "scls",

]
auto-format = true

[[language]]
name = "typescript"
roots = ["package.json"]
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "oxlint",
  "oxfmt",
  "tailwindcss-ls",
  "cspell",
  "scls",
]
auto-format = true

[[language]]
name = "yaml"
roots = ["package.json"]
language-servers = [
  { name = "yaml-language-server", except-features = [
    "format",
  ] },
  "ansible-language-server",
  "oxlint",
  "oxfmt",
  "cspell",
  "scls",
]
auto-format = true

