name: Prepare Environment
description: Install node, pnpm and package dependencies.
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v6
      with:
        cache: pnpm
        node-version: 22
    - shell: bash
      run: pnpm install --frozen-lockfile
    - shell: bash
      run: echo "PLAYWRIGHT_BROWSERS_PATH=${{ github.workspace }}/.cache/ms-playwright" >> "$GITHUB_ENV"
    - uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-playwright-
    - shell: bash
      run: pnpm playwright install --with-deps
