name: Changesets
on:
  push:
    branches: [main]
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  changesets:
    runs-on: ubuntu-latest
    environment: changesets
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: ./repos/konfik/.github/actions/configure_environment
      - run: pnpm run build
      - uses: changesets/action@v1
        with:
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
