name: Check

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: useblacksmith/checkout@v1
      - uses: ./.github/actions/checkout-liminal
      - uses: ./konfik/configure-environment
      - run: pnpm format --check
      - run: pnpm lint
      - run: pnpm build
      - run: pnpm test
