name: Check

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - run: "git -c url.https://github.com/.insteadOf=git@github.com: submodule update --init konfik"
      - uses: crosshatch/konfik/.github/actions/configure_environment@main
      - run: pnpm format --check
      - run: pnpm lint
      - run: pnpm build
      - run: pnpm test
