name: Check

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - run: "git -c url.https://github.com/.insteadOf=git@github.com: submodule update --init konfik"
      - uses: ./konfik/.github/actions/configure_environment
      - run: pnpm build
      # - run: pnpm test
